# Generated by Django 3.2.25 on 2025-01-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='images',
        ),
        migrations.AddField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
